defaults: &defaults
  site:
    name: site name
    root_url: https://sample.com
    sns_account:
      twitter: https://twitter.com/sample
      instagram: https://www.instagram.com/sample
    meta:
      title: page title
      description: description
      keywords: sample1, sample2, sample3
      webclipicon_url: /webclipicon.png
      favicon_url: /favicon.ico
      fb:
        app_id: 9999999999
      og:
        title: page title
        type: website
        image_path: /img/ogp.png
      twitter:
        title: page title
        description: |-
          description
          description #hashtag
        image: /img/ogp.png
        hashtags: hashtag1, hashtag2
  ogp: # 複数ogp
    - index: 1
      title: ogp1 title
      description: ogp1 description
      share_description: ogp1 share_description
    - index: 2
      title: ogp2 title
      description: ogp2 description
      share_description: ogp2 share_description
    - index: 3
      title: ogp3 title
      description: ogp3 description
      share_description: ogp3 share_description

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
