defaults: &defaults
  # 全体ページ
  site:
    name: site name
    root_url: https://sample.com
    meta:
      title: page title
      description: description
      keywords: sample1, sample2, sample3
      webclipicon: /webclipicon.png
      favicon: /favicon.ico
      fb:
        app_id: 9999999999
      og:
        title: page title
        type: website
        image: /img/ogp.png
      twitter:
        title: page title
        description: |-
          description
          #hashtag description
        image: /img/ogp.png
        hashtags: hashtag1, hashtag2
    sns_account:
      twitter: https://twitter.com/sample
      instagram: https://www.instagram.com/sample
  # 個別ページ
  about:
    meta:
      title: about page
      description: about description
      keywords: about1, about2, about3
  # 複数OGP
  ogp:
    - index: 1
      title: ogp1 title
      description: ogp1 description
      share_description: ogp1 share_description
    - index: 2
      title: ogp2 title
      description: ogp2 description
      share_description: ogp2 share_description
    - index: 3
      title: ogp3 title
      description: ogp3 description
      share_description: ogp3 share_description

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
